-- 코드를 입력하세요
SELECT fh.FLAVOR
FROM (SELECT FLAVOR FROM FIRST_HALF WHERE TOTAL_ORDER > 3000 
        ORDER BY TOTAL_ORDER DESC) fh, ICECREAM_INFO ice
WHERE fh.FLAVOR = ice.FLAVOR AND ice.INGREDIENT_TYPE = 'fruit_based'