-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE, 'yyyy-mm-dd') AS PUBLISHED_DATE
FROM BOOK b, AUTHOR a
WHERE b.CATEGORY='경제' and b.AUTHOR_ID = a.AUTHOR_ID
ORDER BY b.PUBLISHED_DATE ASC